CREATE OR ALTER PROCEDURE SHIFT_CALC(@DT_RANGE_BEGIN DATE, @DT_RANGE_END DATE)
AS
BEGIN

TRUNCATE TABLE T_CONTRACTOR_WORK_DAY;

WITH n AS
(
  SELECT TOP (DATEDIFF(DAY, @DT_RANGE_BEGIN, @DT_RANGE_END) + 1) 
    n = ROW_NUMBER() OVER (ORDER BY [object_id])
  FROM sys.all_objects
),
    drange AS
(
	SELECT CAST(DATEADD(DAY, n-1, @DT_RANGE_BEGIN) as DATETIME) as dt
	FROM n
)

INSERT INTO T_CONTRACTOR_WORK_DAY
SELECT	NAME,
		CASE SUBSTRING(SHEDULE, DATEDIFF(DAY, DATE_BEGIN, dt) % LEN(SHEDULE) + 1, 1)
			WHEN N'д' THEN DATEADD(HOUR, 8, dt)
			WHEN N'н' THEN DATEADD(HOUR, 20, dt)
			WHEN N'с' THEN DATEADD(HOUR, 8, dt)
		END as shift_start,
		CASE SUBSTRING(SHEDULE, DATEDIFF(DAY, DATE_BEGIN, dt) % LEN(SHEDULE) + 1, 1)
			WHEN N'д' THEN DATEADD(HOUR, 20, dt)
			WHEN N'н' THEN DATEADD(HOUR, 32, dt)
			WHEN N'с' THEN DATEADD(HOUR, 32, dt)
		END as shift_end
FROM drange
JOIN T_CONTRACTOR_SHERULER t
ON drange.dt BETWEEN DATE_BEGIN AND DATE_END 
WHERE SUBSTRING(SHEDULE, DATEDIFF(DAY, DATE_BEGIN, dt) % LEN(SHEDULE) + 1, 1) <> N'в'

END
